"""Extract user profile from auto-memory + portfolio + preferences → USER.md.

Aggregates structured info from:
  - C:\\Users\\paidu\\.claude\\projects\\C--Users-paidu-investment-intelligence\\memory\\
    (auto-memory: feedback_*.md, user_*.md)
  - portfolio_positions table (BR + US, current holdings count + currencies)
  - config/agents.yaml (agent count)
  - obsidian_vault/CONSTITUTION.md (current phase)

Writes:  obsidian_vault/workspace/USER.md  (overwrites)

Idempotent — same inputs produce same output. Safe to re-run.

Hot-reloaded by chief_of_staff on every invocation (no daemon restart needed).
"""
from __future__ import annotations

import os
import sqlite3
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
USER_MD_PATH = ROOT / "obsidian_vault" / "workspace" / "USER.md"
AUTO_MEMORY_DIR = Path(os.path.expanduser(
    "~/.claude/projects/C--Users-paidu-investment-intelligence/memory"
))
CONSTITUTION_PATH = ROOT / "obsidian_vault" / "CONSTITUTION.md"
AGENTS_YAML = ROOT / "config" / "agents.yaml"


def _portfolio_summary() -> dict:
    """Count active positions per market, return summary dict."""
    out = {"br": 0, "us": 0, "br_total_brl": 0.0, "us_total_usd": 0.0}
    for mkt, db in [("br", "br_investments.db"), ("us", "us_investments.db")]:
        p = ROOT / "data" / db
        if not p.exists():
            continue
        try:
            with sqlite3.connect(p) as c:
                row = c.execute(
                    "SELECT COUNT(*), COALESCE(SUM(quantity*entry_price), 0) "
                    "FROM portfolio_positions WHERE active=1"
                ).fetchone()
                out[mkt] = row[0]
                out[f"{mkt}_total_{'brl' if mkt=='br' else 'usd'}"] = round(row[1] or 0.0, 2)
        except Exception:
            pass
    return out


def _scan_feedback_memories() -> list[str]:
    """One-line summaries of feedback_*.md memory files (rules/preferences)."""
    if not AUTO_MEMORY_DIR.exists():
        return []
    out: list[str] = []
    for f in sorted(AUTO_MEMORY_DIR.glob("feedback_*.md")):
        try:
            text = f.read_text(encoding="utf-8")
        except Exception:
            continue
        # Pull description from frontmatter or first non-empty body line
        title = f.stem.replace("feedback_", "").replace("_", " ")
        desc = ""
        in_frontmatter = False
        for line in text.splitlines():
            line = line.strip()
            if line == "---":
                in_frontmatter = not in_frontmatter
                continue
            if in_frontmatter and line.startswith("description:"):
                desc = line.split(":", 1)[1].strip().strip('"')
                break
            if not in_frontmatter and line and not line.startswith("#") and not desc:
                desc = line[:140]
                break
        out.append(f"- **{title}** — {desc}" if desc else f"- **{title}**")
    return out


def _user_role_files() -> list[str]:
    """Direct user_*.md files content snippets."""
    if not AUTO_MEMORY_DIR.exists():
        return []
    out: list[str] = []
    for f in sorted(AUTO_MEMORY_DIR.glob("user_*.md")):
        try:
            text = f.read_text(encoding="utf-8")
        except Exception:
            continue
        # Strip frontmatter, keep first 300 chars of body
        body = text
        if body.startswith("---"):
            parts = body.split("---", 2)
            if len(parts) >= 3:
                body = parts[2].strip()
        body = body.replace("#", "").strip()[:280]
        out.append(f"### {f.stem}\n\n{body}")
    return out


def _current_phase() -> str:
    if not CONSTITUTION_PATH.exists():
        return "(no constitution)"
    try:
        text = CONSTITUTION_PATH.read_text(encoding="utf-8")
    except Exception:
        return "(unreadable constitution)"
    for line in text.splitlines():
        if line.startswith("## ") and "Phase" in line:
            return line.lstrip("# ").strip()
    return "(no phase header)"


def _agent_count() -> int:
    if not AGENTS_YAML.exists():
        return 0
    try:
        text = AGENTS_YAML.read_text(encoding="utf-8")
    except Exception:
        return 0
    return text.count("\n  - name:")


def render() -> str:
    portfolio = _portfolio_summary()
    feedback = _scan_feedback_memories()
    user_files = _user_role_files()
    phase = _current_phase()
    agent_count = _agent_count()
    today = date.today().isoformat()

    lines = [
        "---",
        "title: USER",
        f"generated: {today}",
        "purpose: Profile do founder. Carregado em main session (DM), NUNCA em group chats ou broadcast.",
        "edit: regenerated by scripts/extract_user_profile.py; humano-editável overrides bem-vindos.",
        "---",
        "",
        "# USER — Sobre o founder",
        "",
        "- **Name**: Andre Paidusis",
        "- **What to call them**: Andre / founder",
        "- **Email**: apaidusis@gmail.com",
        "- **Timezone**: Europe/Lisbon",
        "- **Hardware always-on**: Ryzen 9800X3D + RTX 5090, Windows 11",
        "",
        "## Investment context",
        "",
        f"- **Carteira BR**: {portfolio['br']} posições activas (R$ {portfolio['br_total_brl']:,.0f} cost basis)",
        f"- **Carteira US**: {portfolio['us']} posições activas (US$ {portfolio['us_total_usd']:,.0f} cost basis)",
        "- **Filosofia**: DRIP / Buffett / Graham — long-term, qualidade, dividendos consistentes.",
        "- **Carteiras BR e US isoladas** (BRL fica em BR, USD fica em US). Nunca sugerir conversão.",
        "- **Universe central**: `config/universe.yaml` — toda edição de tickers passa aí.",
        "",
        "## System state",
        "",
        f"- **Agents registered**: {agent_count} em config/agents.yaml",
        f"- **Active phase**: {phase}",
        "",
        "## Preferências (extraídas de auto-memory feedback files)",
        "",
        *feedback,
        "",
    ]
    if user_files:
        lines.append("## Role / context (user_*.md memory)")
        lines.append("")
        lines.extend(user_files)
        lines.append("")
    lines += [
        "---",
        "",
        f"_Generated by `scripts/extract_user_profile.py` em {today}. Re-run para refresh._",
    ]
    return "\n".join(lines)


def main() -> int:
    out = render()
    USER_MD_PATH.parent.mkdir(parents=True, exist_ok=True)
    USER_MD_PATH.write_text(out, encoding="utf-8")
    print(f"wrote {len(out)} chars to {USER_MD_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
